name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install imagemagick
      run: brew install imagemagick
    - name: Install librsvg
      run: brew install librsvg
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
